version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - supertetris-network

  # Python Game Server
  python-server:
    build:
      context: .
      dockerfile: src/python_server/Dockerfile
    image: supertetris-python-server:latest
    ports:
      - "8003:8003"
    volumes:
      - ./src/python_server:/app
    environment:
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - supertetris-network

  # Python Game Logic
  python-logic:
    build:
      context: .
      dockerfile: src/python_logic/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/python_logic:/app
    environment:
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/app
    depends_on:
      - postgres
      - redis
    networks:
      - supertetris-network

  # TypeScript Client
  typescript-client:
    build:
      context: ./src/python_tools
      dockerfile: Dockerfile
    image: supertetris-client:latest
    ports:
      - "5173:80"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - API_URL=http://python-server:8003
      - WS_URL=ws://python-server:8003/ws
    depends_on:
      - python-server
    networks:
      - supertetris-network

  # Python Analytics
  python-analytics:
    build:
      context: .
      dockerfile: src/python_analytics/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tetris_analytics
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - supertetris-network

  # Python AI
  python-ai:
    build:
      context: .
      dockerfile: src/python_ai/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./src/python_ai/models:/app/models
      - ./src/python_ai/training_data:/app/training_data
    environment:
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/app
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8001
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - supertetris-network

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=tetris_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - supertetris-network

  # Python Development Tools
  python-tools:
    build:
      context: ./src/python_tools
      dockerfile: Dockerfile
    image: supertetris-python-tools:latest
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tetris_analytics
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/dev/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - supertetris-network

volumes:
  redis_data:
  postgres_data:

networks:
  supertetris-network:
    driver: bridge
